#include "../src/tir.h"
#include "../src/qasm.h"
#include "../src/qasm_lex.h"
#include "../src/qasm_parse.h"
#include "../src/mnote.h"
#include "demos.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/*
 * The Qiskit corpus test.
 *
 * Reads each .qasm file in test/qiskit_corpus/samples, hands it to
 * Ernest's lexer and parser, and reports what survived the trip.
 * The corpus was generated by qiskit.qasm3.dumps on a deliberate
 * spread of circuits: friendly ones (Bell, GHZ), rotation-heavy
 * ones (QFT, VQE ansatz), and a few featuring gates that Ernest
 * hasn't met before (Toffoli, controlled-Hadamard, controlled-phase).
 *
 * The point of this exercise is not to score a 12/12; it's to find
 * the precise places where Ernest stops being able to read what
 * Qiskit writes, so we know what to fix next. A clean self-parse
 * means very little if the parser falls over on the first real
 * input. Better to know now.
 */

#define CORPUS_BUF_MAX  (1u << 16)
#define CORPUS_DIR      "test/qiskit_corpus/samples"

typedef enum {
    CORPUS_PASS       = 0,
    CORPUS_LEX_FAIL   = 1,
    CORPUS_PARSE_FAIL = 2,
    CORPUS_IO_FAIL    = 3
} corpus_result_t;

typedef struct {
    const char *filename;
    const char *desc;     /* one-line description for the report */
} corpus_entry_t;

/*
 * The corpus. Order shades from easy (top) to hard (bottom). If the
 * report lights up red the further down it goes, the parser is doing
 * about what we'd expect.
 */
static const corpus_entry_t CORPUS[] = {
    { "bell.qasm",                "Bell state"                       },
    { "ghz_5.qasm",               "five-qubit GHZ"                   },
    { "deutsch.qasm",             "Deutsch's algorithm"              },
    { "grover_2q.qasm",           "two-qubit Grover"                 },
    { "rotations_only.qasm",      "all three rotation axes"          },
    { "clifford_small.qasm",      "small Clifford circuit"           },
    { "bernstein_vazirani.qasm",  "Bernstein-Vazirani, secret 1011"  },
    { "multireg.qasm",            "multiple named registers"         },
    { "vqe_ansatz.qasm",          "EfficientSU2 ansatz, bound"       },
    { "qft_4.qasm",               "four-qubit QFT (uses cp gate)"    },
    { "w_state.qasm",             "W state (uses ch gate)"           },
    { "toffoli.qasm",             "Toffoli (uses ccx gate)"          },
};

#define NUM_CORPUS (sizeof CORPUS / sizeof CORPUS[0])

/*
 * Big static state. Per-run, not per-file; the harness re-initialises
 * each between samples.
 */
static char         corpus_buf[CORPUS_BUF_MAX];
static qasm_lexer_t corpus_lex;
static tir_module_t corpus_M;
static mnote_log_t  corpus_log_lex;
static mnote_log_t  corpus_log_parse;

/* Read a file into the supplied buffer. Returns bytes read, zero on
 * any error. */
static size_t read_file(const char *path, char *buf, size_t cap)
{
    assert(path != NULL);
    assert(buf  != NULL);
    assert(cap  > 1u);

    FILE *f = fopen(path, "rb");
    if (f == NULL) {
        return 0u;
    }
    size_t n = fread(buf, 1u, cap - 1u, f);
    (void)fclose(f);
    buf[n] = '\0';
    return n;
}

/*
 * Run one corpus file through lex and parse, write a short reason
 * string into `reason`, return the result enum.
 */
static corpus_result_t test_one(const corpus_entry_t *E,
                                char *reason, size_t reason_cap)
{
    assert(E      != NULL);
    assert(reason != NULL);

    char path[256];
    (void)snprintf(path, sizeof path, "%s/%s", CORPUS_DIR, E->filename);

    size_t n = read_file(path, corpus_buf, (size_t)CORPUS_BUF_MAX);
    if (n == 0u) {
        (void)snprintf(reason, reason_cap, "cannot open %.200s", path);
        return CORPUS_IO_FAIL;
    }

    /* Lex. */
    mnote_init(&corpus_log_lex, "ERNESTLX");
    qasm_lex_init(&corpus_lex, corpus_buf, (uint32_t)n,
                  E->filename, &corpus_log_lex);
    int lex_rc = qasm_lex_run(&corpus_lex);
    if (lex_rc >= 8) {
        if (corpus_log_lex.num_notes > 0u) {
            (void)snprintf(reason, reason_cap, "LEX: %.230s",
                           corpus_log_lex.notes[0].message);
        } else {
            (void)snprintf(reason, reason_cap, "LEX failed RC=%d", lex_rc);
        }
        return CORPUS_LEX_FAIL;
    }

    /* Parse. */
    tir_module_init(&corpus_M, E->filename);
    mnote_init(&corpus_log_parse, "ERNESTPR");
    int parse_rc = qasm_parse(&corpus_lex, &corpus_M, &corpus_log_parse);
    if (parse_rc >= 8) {
        if (corpus_log_parse.num_notes > 0u) {
            (void)snprintf(reason, reason_cap, "PARSE: %.228s",
                           corpus_log_parse.notes[0].message);
        } else {
            (void)snprintf(reason, reason_cap, "PARSE failed RC=%d", parse_rc);
        }
        return CORPUS_PARSE_FAIL;
    }

    (void)snprintf(reason, reason_cap, "%u insts, %u toks",
                   (unsigned)corpus_M.num_insts,
                   (unsigned)corpus_lex.num_tokens);
    return CORPUS_PASS;
}

int run_corpus_test(void)
{
    uint32_t pass       = 0u;
    uint32_t lex_fail   = 0u;
    uint32_t parse_fail = 0u;
    uint32_t io_fail    = 0u;

    (void)printf("ERNESTJB CORP START -----------------------------\n");
    (void)printf("\nQiskit corpus test  (%u files from %s)\n",
                 (unsigned)NUM_CORPUS, CORPUS_DIR);
    (void)printf("-----------------------------------------------------------\n");

    for (uint32_t i = 0u; i < (uint32_t)NUM_CORPUS; i++) {
        const corpus_entry_t *E = &CORPUS[i];
        char reason[256];
        corpus_result_t r = test_one(E, reason, sizeof reason);

        const char *status;
        switch (r) {
        case CORPUS_PASS:       status = " PASS";   pass++;       break;
        case CORPUS_LEX_FAIL:   status = "LFAIL";   lex_fail++;   break;
        case CORPUS_PARSE_FAIL: status = "PFAIL";   parse_fail++; break;
        case CORPUS_IO_FAIL:    status = "IOERR";   io_fail++;    break;
        default:                status = " ????";                 break;
        }

        (void)printf("  [%s] %-26s  %s\n", status, E->filename, reason);
    }

    (void)printf("-----------------------------------------------------------\n");
    (void)printf("ERNEST CORPUS  PASS=%u  PFAIL=%u  LFAIL=%u  IOERR=%u  OF=%u\n",
                 (unsigned)pass, (unsigned)parse_fail,
                 (unsigned)lex_fail, (unsigned)io_fail,
                 (unsigned)NUM_CORPUS);

    uint32_t rc = (pass == (uint32_t)NUM_CORPUS) ? 0u : 4u;
    (void)printf("ERNEST EOJ     RC=%u\n", (unsigned)rc);
    return (int)rc;
}
