#include "aot.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>

/*
 * The AOT codegen. Walk the TIR module and write a self-contained
 * C program that runs the circuit. The generated program is then
 * compiled with gcc -O3 and executed. Output of the executed binary
 * is parsed back into the counts array.
 *
 * Each gate is emitted as a call to an inline helper defined at the
 * top of the generated file. The helpers are byte-for-byte the same
 * mathematics as sim.c, just inlined into a tighter loop and freed
 * from the per-instruction switch.
 */

/* fopen and gcc accept forward slashes on every platform; the
 * trouble is Windows cmd.exe, which popen delegates to, treats
 * forward-slash paths as flag characters. So we keep forward
 * slashes for the gcc compile command and for fopen, but use
 * native separators for the executable's path when handing it
 * to popen. */
#define AOT_TEMP_C    "build/aot_circuit.c"
#ifdef _WIN32
#define AOT_TEMP_BIN  "build/aot_circuit.exe"
#define AOT_RUN_CMD   "build\\aot_circuit.exe"
#else
#define AOT_TEMP_BIN  "build/aot_circuit"
#define AOT_RUN_CMD   "./build/aot_circuit"
#endif
/*
 * -fno-tree-vectorize is load-bearing. Without it, gcc's loop and
 * SLP vectorisers reorder floating-point additions in ways that
 * preserve IEEE 754 individually but compound numerical error
 * across long phase-rotation circuits. On the QFT round-trip test
 * the difference is dramatic: vectorised -O3 produced 87% on the
 * correct outcome with 13% leakage; -O3 -fno-tree-vectorize
 * produces 99.99% on the correct outcome. We keep the rest of -O3
 * (inlining, register allocation, scalar optimisations) which buys
 * most of the speed. */
#define AOT_GCC_CMD   "gcc -O3 -fno-tree-vectorize -std=c99 -o " \
                      AOT_TEMP_BIN " " AOT_TEMP_C " -lm"

/* Emit the unchanging prelude: includes, constants, statevector
 * arrays, and the gate helper functions. Sizes the arrays for the
 * exact dimensions of M so the C compiler can constant-fold the
 * bounds. */
static void emit_prelude(const tir_module_t *M, FILE *out, uint32_t shots)
{
    uint32_t nq = tir_total_qubits(M);
    uint32_t nb = tir_total_bits(M);
    if (nq == 0u) nq = 1u;          /* allow empty circuits to compile */
    if (nb == 0u) nb = 1u;
    uint32_t dim     = 1u << nq;
    uint32_t outcomes = 1u << nb;

    (void)fprintf(out,
        "/* Generated by Ernest AOT.  Do not edit; regenerate. */\n"
        "#include <stdio.h>\n"
        "#include <stdlib.h>\n"
        "#include <math.h>\n"
        "#include <time.h>\n"
        "\n"
        "#define NQ %u\n"
        "#define NB %u\n"
        "#define DIM %uu\n"
        "#define NUM_OUTCOMES %uu\n"
        "#define DEFAULT_SHOTS %uu\n"
        "\n"
        "static const double INV_SQRT2 = 0.70710678118654752440;\n"
        "static const double M_PI_LOCAL = 3.14159265358979323846;\n"
        "\n"
        "static double state_re[DIM];\n"
        "static double state_im[DIM];\n"
        "static unsigned bits[NB];\n"
        "static unsigned counts[NUM_OUTCOMES];\n"
        "\n",
        (unsigned)nq, (unsigned)nb, (unsigned)dim,
        (unsigned)outcomes, (unsigned)shots);

    /* Single-qubit gates: H, X, Y, Z, S, T, SDG, TDG, SX. */
    (void)fprintf(out,
        "static inline void apply_h(unsigned q) {\n"
        "    unsigned mask = 1u << q;\n"
        "    for (unsigned i = 0; i < DIM; i++) {\n"
        "        if (i & mask) continue;\n"
        "        unsigned j = i | mask;\n"
        "        double ar = state_re[i], ai = state_im[i];\n"
        "        double br = state_re[j], bi = state_im[j];\n"
        "        state_re[i] = INV_SQRT2 * (ar + br);\n"
        "        state_im[i] = INV_SQRT2 * (ai + bi);\n"
        "        state_re[j] = INV_SQRT2 * (ar - br);\n"
        "        state_im[j] = INV_SQRT2 * (ai - bi);\n"
        "    }\n"
        "}\n"
        "\n"
        "static inline void apply_x(unsigned q) {\n"
        "    unsigned mask = 1u << q;\n"
        "    for (unsigned i = 0; i < DIM; i++) {\n"
        "        if (i & mask) continue;\n"
        "        unsigned j = i | mask;\n"
        "        double tr = state_re[i], ti = state_im[i];\n"
        "        state_re[i] = state_re[j]; state_im[i] = state_im[j];\n"
        "        state_re[j] = tr; state_im[j] = ti;\n"
        "    }\n"
        "}\n"
        "\n"
        "static inline void apply_y(unsigned q) {\n"
        "    unsigned mask = 1u << q;\n"
        "    for (unsigned i = 0; i < DIM; i++) {\n"
        "        if (i & mask) continue;\n"
        "        unsigned j = i | mask;\n"
        "        double ar = state_re[i], ai = state_im[i];\n"
        "        double br = state_re[j], bi = state_im[j];\n"
        "        /* Y = [[0,-i],[i,0]] */\n"
        "        state_re[i] =  bi;  state_im[i] = -br;\n"
        "        state_re[j] = -ai;  state_im[j] =  ar;\n"
        "    }\n"
        "}\n"
        "\n"
        "static inline void apply_z(unsigned q) {\n"
        "    unsigned mask = 1u << q;\n"
        "    for (unsigned i = 0; i < DIM; i++) {\n"
        "        if (i & mask) { state_re[i] = -state_re[i]; state_im[i] = -state_im[i]; }\n"
        "    }\n"
        "}\n"
        "\n"
        "static inline void apply_phase(unsigned q, double c, double s) {\n"
        "    unsigned mask = 1u << q;\n"
        "    for (unsigned i = 0; i < DIM; i++) {\n"
        "        if (!(i & mask)) continue;\n"
        "        double r = state_re[i], m = state_im[i];\n"
        "        state_re[i] = r * c - m * s;\n"
        "        state_im[i] = r * s + m * c;\n"
        "    }\n"
        "}\n"
        "\n"
        "static inline void apply_s(unsigned q)   { apply_phase(q, 0.0,  1.0); }\n"
        "static inline void apply_sdg(unsigned q) { apply_phase(q, 0.0, -1.0); }\n"
        "static inline void apply_t(unsigned q)   { apply_phase(q,  INV_SQRT2,  INV_SQRT2); }\n"
        "static inline void apply_tdg(unsigned q) { apply_phase(q,  INV_SQRT2, -INV_SQRT2); }\n"
        "\n"
        "static inline void apply_sx(unsigned q) {\n"
        "    unsigned mask = 1u << q;\n"
        "    for (unsigned i = 0; i < DIM; i++) {\n"
        "        if (i & mask) continue;\n"
        "        unsigned j = i | mask;\n"
        "        double ar = state_re[i], ai = state_im[i];\n"
        "        double br = state_re[j], bi = state_im[j];\n"
        "        /* SX = ((1+i)/2)[[1,-i],[-i,1]] */\n"
        "        state_re[i] = 0.5*(ar - ai + br + bi);\n"
        "        state_im[i] = 0.5*(ar + ai - br + bi);\n"
        "        state_re[j] = 0.5*(ar + ai + br - bi);\n"
        "        state_im[j] = 0.5*(-ar + ai + br + bi);\n"
        "    }\n"
        "}\n"
        "\n");

    /* Rotation gates. */
    (void)fprintf(out,
        "static inline void apply_rx(unsigned q, double theta) {\n"
        "    double c = cos(theta*0.5), s = sin(theta*0.5);\n"
        "    unsigned mask = 1u << q;\n"
        "    for (unsigned i = 0; i < DIM; i++) {\n"
        "        if (i & mask) continue;\n"
        "        unsigned j = i | mask;\n"
        "        double ar = state_re[i], ai = state_im[i];\n"
        "        double br = state_re[j], bi = state_im[j];\n"
        "        state_re[i] = c*ar + s*bi;\n"
        "        state_im[i] = c*ai - s*br;\n"
        "        state_re[j] = s*ai + c*br;\n"
        "        state_im[j] = -s*ar + c*bi;\n"
        "    }\n"
        "}\n"
        "\n"
        "static inline void apply_ry(unsigned q, double theta) {\n"
        "    double c = cos(theta*0.5), s = sin(theta*0.5);\n"
        "    unsigned mask = 1u << q;\n"
        "    for (unsigned i = 0; i < DIM; i++) {\n"
        "        if (i & mask) continue;\n"
        "        unsigned j = i | mask;\n"
        "        double ar = state_re[i], ai = state_im[i];\n"
        "        double br = state_re[j], bi = state_im[j];\n"
        "        state_re[i] = c*ar - s*br;\n"
        "        state_im[i] = c*ai - s*bi;\n"
        "        state_re[j] = s*ar + c*br;\n"
        "        state_im[j] = s*ai + c*bi;\n"
        "    }\n"
        "}\n"
        "\n"
        "static inline void apply_rz(unsigned q, double theta) {\n"
        "    double c = cos(theta*0.5), s = sin(theta*0.5);\n"
        "    unsigned mask = 1u << q;\n"
        "    for (unsigned i = 0; i < DIM; i++) {\n"
        "        double r = state_re[i], m = state_im[i];\n"
        "        if (i & mask) {\n"
        "            state_re[i] = c*r - s*m;\n"
        "            state_im[i] = c*m + s*r;\n"
        "        } else {\n"
        "            state_re[i] = c*r + s*m;\n"
        "            state_im[i] = c*m - s*r;\n"
        "        }\n"
        "    }\n"
        "}\n"
        "\n");

    /* Two-qubit gates. */
    (void)fprintf(out,
        "static inline void apply_cx(unsigned ctrl, unsigned tgt) {\n"
        "    unsigned cm = 1u << ctrl;\n"
        "    unsigned tm = 1u << tgt;\n"
        "    for (unsigned i = 0; i < DIM; i++) {\n"
        "        if (!(i & cm)) continue;\n"
        "        unsigned j = i ^ tm;\n"
        "        if (j > i) {\n"
        "            double tr = state_re[i], ti = state_im[i];\n"
        "            state_re[i] = state_re[j]; state_im[i] = state_im[j];\n"
        "            state_re[j] = tr; state_im[j] = ti;\n"
        "        }\n"
        "    }\n"
        "}\n"
        "\n"
        "static inline void apply_cz(unsigned ctrl, unsigned tgt) {\n"
        "    unsigned mask = (1u << ctrl) | (1u << tgt);\n"
        "    for (unsigned i = 0; i < DIM; i++) {\n"
        "        if ((i & mask) == mask) { state_re[i] = -state_re[i]; state_im[i] = -state_im[i]; }\n"
        "    }\n"
        "}\n"
        "\n"
        "static inline void apply_ch(unsigned ctrl, unsigned tgt) {\n"
        "    unsigned cm = 1u << ctrl;\n"
        "    unsigned tm = 1u << tgt;\n"
        "    for (unsigned i = 0; i < DIM; i++) {\n"
        "        if (!(i & cm)) continue;\n"
        "        if (i & tm) continue;\n"
        "        unsigned j = i | tm;\n"
        "        double ar = state_re[i], ai = state_im[i];\n"
        "        double br = state_re[j], bi = state_im[j];\n"
        "        state_re[i] = INV_SQRT2 * (ar + br);\n"
        "        state_im[i] = INV_SQRT2 * (ai + bi);\n"
        "        state_re[j] = INV_SQRT2 * (ar - br);\n"
        "        state_im[j] = INV_SQRT2 * (ai - bi);\n"
        "    }\n"
        "}\n"
        "\n"
        "static inline void apply_cp(unsigned ctrl, unsigned tgt, double theta) {\n"
        "    unsigned mask = (1u << ctrl) | (1u << tgt);\n"
        "    double c = cos(theta), s = sin(theta);\n"
        "    for (unsigned i = 0; i < DIM; i++) {\n"
        "        if ((i & mask) != mask) continue;\n"
        "        double r = state_re[i], m = state_im[i];\n"
        "        state_re[i] = r*c - m*s;\n"
        "        state_im[i] = r*s + m*c;\n"
        "    }\n"
        "}\n"
        "\n"
        "static inline void apply_swap(unsigned a, unsigned b) {\n"
        "    unsigned ma = 1u << a;\n"
        "    unsigned mb = 1u << b;\n"
        "    for (unsigned i = 0; i < DIM; i++) {\n"
        "        unsigned ba = (i & ma) != 0;\n"
        "        unsigned bb = (i & mb) != 0;\n"
        "        if (ba == bb) continue;\n"
        "        unsigned j = i ^ ma ^ mb;\n"
        "        if (j > i) {\n"
        "            double tr = state_re[i], ti = state_im[i];\n"
        "            state_re[i] = state_re[j]; state_im[i] = state_im[j];\n"
        "            state_re[j] = tr; state_im[j] = ti;\n"
        "        }\n"
        "    }\n"
        "}\n"
        "\n"
        "static inline void apply_ccx(unsigned c1, unsigned c2, unsigned tgt) {\n"
        "    unsigned cm = (1u << c1) | (1u << c2);\n"
        "    unsigned tm = 1u << tgt;\n"
        "    for (unsigned i = 0; i < DIM; i++) {\n"
        "        if ((i & cm) != cm) continue;\n"
        "        unsigned j = i ^ tm;\n"
        "        if (j > i) {\n"
        "            double tr = state_re[i], ti = state_im[i];\n"
        "            state_re[i] = state_re[j]; state_im[i] = state_im[j];\n"
        "            state_re[j] = tr; state_im[j] = ti;\n"
        "        }\n"
        "    }\n"
        "}\n"
        "\n");

    /* Measurement and reset. */
    (void)fprintf(out,
        "static inline void measure_q(unsigned q, unsigned bit_idx) {\n"
        "    unsigned mask = 1u << q;\n"
        "    double p1 = 0.0;\n"
        "    for (unsigned i = 0; i < DIM; i++) {\n"
        "        if (i & mask) p1 += state_re[i]*state_re[i] + state_im[i]*state_im[i];\n"
        "    }\n"
        "    double r = (double)rand() / (double)RAND_MAX;\n"
        "    unsigned outcome = (r < p1) ? 1u : 0u;\n"
        "    double norm = outcome ? p1 : (1.0 - p1);\n"
        "    if (norm <= 0.0) { outcome ^= 1u; norm = outcome ? p1 : (1.0 - p1); }\n"
        "    double inv = 1.0 / sqrt(norm);\n"
        "    for (unsigned i = 0; i < DIM; i++) {\n"
        "        unsigned b = (i & mask) ? 1u : 0u;\n"
        "        if (b != outcome) { state_re[i] = 0.0; state_im[i] = 0.0; }\n"
        "        else { state_re[i] *= inv; state_im[i] *= inv; }\n"
        "    }\n"
        "    bits[bit_idx] = outcome;\n"
        "}\n"
        "\n"
        "static inline void reset_q(unsigned q) {\n"
        "    unsigned mask = 1u << q;\n"
        "    double p1 = 0.0;\n"
        "    for (unsigned i = 0; i < DIM; i++) {\n"
        "        if (i & mask) p1 += state_re[i]*state_re[i] + state_im[i]*state_im[i];\n"
        "    }\n"
        "    double r = (double)rand() / (double)RAND_MAX;\n"
        "    unsigned outcome = (r < p1) ? 1u : 0u;\n"
        "    double norm = outcome ? p1 : (1.0 - p1);\n"
        "    if (norm <= 0.0) { outcome ^= 1u; norm = outcome ? p1 : (1.0 - p1); }\n"
        "    double inv = 1.0 / sqrt(norm);\n"
        "    for (unsigned i = 0; i < DIM; i++) {\n"
        "        unsigned b = (i & mask) ? 1u : 0u;\n"
        "        if (b != outcome) { state_re[i] = 0.0; state_im[i] = 0.0; }\n"
        "        else { state_re[i] *= inv; state_im[i] *= inv; }\n"
        "    }\n"
        "    if (outcome) apply_x(q);\n"
        "}\n"
        "\n");
}

/*
 * Map a TIR qubit reference to its flat index. Decomposes the ref
 * into (register, offset) and walks the qreg table to compute the
 * cumulative base. Identical logic to tir_flat_qubit_index, which
 * we duplicate here because the codegen is static.
 */
static uint32_t flat_q(const tir_module_t *M, uint32_t qref)
{
    uint32_t r = TIR_REF_REG(qref);
    uint32_t i = TIR_REF_IDX(qref);
    uint32_t base = 0u;
    for (uint32_t k = 0u; k < r; k++) {
        base += M->qregs[k].width;
    }
    return base + i;
}

static uint32_t flat_b(const tir_module_t *M, uint32_t cref)
{
    uint32_t r = TIR_REF_REG(cref);
    uint32_t i = TIR_REF_IDX(cref);
    uint32_t base = 0u;
    for (uint32_t k = 0u; k < r; k++) {
        base += M->cregs[k].width;
    }
    return base + i;
}

/*
 * Emit the run_shot function: zero the statevector, apply each gate
 * in order. Each TIR instruction becomes one line of C.
 */
static void emit_run_shot(const tir_module_t *M, FILE *out)
{
    (void)fprintf(out,
        "static void run_shot(void) {\n"
        "    for (unsigned i = 0; i < DIM; i++) { state_re[i] = 0.0; state_im[i] = 0.0; }\n"
        "    state_re[0] = 1.0;\n"
        "    for (unsigned i = 0; i < NB; i++) bits[i] = 0;\n"
        "\n");

    uint32_t n = M->num_insts;
    for (uint32_t i = 0u; i < n; i++) {
        const tir_inst_t *I = &M->insts[i];
        switch ((tir_op_t)I->op) {
        case TIR_QREG_DECL:
        case TIR_CREG_DECL:
            /* declarations contribute to the prelude's DIM/NB, no
             * body code needed */
            break;
        case TIR_GATE_H:
            (void)fprintf(out, "    apply_h(%u);\n", (unsigned)flat_q(M, I->operands[0]));
            break;
        case TIR_GATE_X:
            (void)fprintf(out, "    apply_x(%u);\n", (unsigned)flat_q(M, I->operands[0]));
            break;
        case TIR_GATE_Y:
            (void)fprintf(out, "    apply_y(%u);\n", (unsigned)flat_q(M, I->operands[0]));
            break;
        case TIR_GATE_Z:
            (void)fprintf(out, "    apply_z(%u);\n", (unsigned)flat_q(M, I->operands[0]));
            break;
        case TIR_GATE_S:
            (void)fprintf(out, "    apply_s(%u);\n", (unsigned)flat_q(M, I->operands[0]));
            break;
        case TIR_GATE_T:
            (void)fprintf(out, "    apply_t(%u);\n", (unsigned)flat_q(M, I->operands[0]));
            break;
        case TIR_GATE_SDG:
            (void)fprintf(out, "    apply_sdg(%u);\n", (unsigned)flat_q(M, I->operands[0]));
            break;
        case TIR_GATE_TDG:
            (void)fprintf(out, "    apply_tdg(%u);\n", (unsigned)flat_q(M, I->operands[0]));
            break;
        case TIR_GATE_SX:
            (void)fprintf(out, "    apply_sx(%u);\n", (unsigned)flat_q(M, I->operands[0]));
            break;
        case TIR_GATE_RX:
            (void)fprintf(out, "    apply_rx(%u, %.17g);\n",
                          (unsigned)flat_q(M, I->operands[0]),
                          M->angles[I->operands[1]]);
            break;
        case TIR_GATE_RY:
            (void)fprintf(out, "    apply_ry(%u, %.17g);\n",
                          (unsigned)flat_q(M, I->operands[0]),
                          M->angles[I->operands[1]]);
            break;
        case TIR_GATE_RZ:
            (void)fprintf(out, "    apply_rz(%u, %.17g);\n",
                          (unsigned)flat_q(M, I->operands[0]),
                          M->angles[I->operands[1]]);
            break;
        case TIR_GATE_CX:
            (void)fprintf(out, "    apply_cx(%u, %u);\n",
                          (unsigned)flat_q(M, I->operands[0]),
                          (unsigned)flat_q(M, I->operands[1]));
            break;
        case TIR_GATE_CZ:
            (void)fprintf(out, "    apply_cz(%u, %u);\n",
                          (unsigned)flat_q(M, I->operands[0]),
                          (unsigned)flat_q(M, I->operands[1]));
            break;
        case TIR_GATE_CH:
            (void)fprintf(out, "    apply_ch(%u, %u);\n",
                          (unsigned)flat_q(M, I->operands[0]),
                          (unsigned)flat_q(M, I->operands[1]));
            break;
        case TIR_GATE_CP:
            (void)fprintf(out, "    apply_cp(%u, %u, %.17g);\n",
                          (unsigned)flat_q(M, I->operands[0]),
                          (unsigned)flat_q(M, I->operands[1]),
                          M->angles[I->operands[2]]);
            break;
        case TIR_GATE_SWAP:
            (void)fprintf(out, "    apply_swap(%u, %u);\n",
                          (unsigned)flat_q(M, I->operands[0]),
                          (unsigned)flat_q(M, I->operands[1]));
            break;
        case TIR_GATE_CCX:
            (void)fprintf(out, "    apply_ccx(%u, %u, %u);\n",
                          (unsigned)flat_q(M, I->operands[0]),
                          (unsigned)flat_q(M, I->operands[1]),
                          (unsigned)flat_q(M, I->operands[2]));
            break;
        case TIR_MEASURE:
            (void)fprintf(out, "    measure_q(%u, %u);\n",
                          (unsigned)flat_q(M, I->operands[0]),
                          (unsigned)flat_b(M, I->operands[1]));
            break;
        case TIR_RESET:
            (void)fprintf(out, "    reset_q(%u);\n",
                          (unsigned)flat_q(M, I->operands[0]));
            break;
        case TIR_OP_COUNT:
        default:
            (void)fprintf(out, "    /* unknown op %u */\n", (unsigned)I->op);
            break;
        }
    }
    (void)fprintf(out, "}\n\n");
}

/*
 * Emit main(). Reads optional shot count from argv[1], seeds the
 * RNG once, runs the shots, prints counts as "outcome count" lines
 * on stdout. The driver back in Ernest parses those lines into the
 * caller's counts array.
 */
static void emit_main(FILE *out)
{
    (void)fprintf(out,
        "int main(int argc, char **argv) {\n"
        "    unsigned shots = DEFAULT_SHOTS;\n"
        "    if (argc > 1) {\n"
        "        long s = strtol(argv[1], NULL, 10);\n"
        "        if (s > 0 && s < 100000000) shots = (unsigned)s;\n"
        "    }\n"
        "    srand((unsigned)time(NULL));\n"
        "    for (unsigned s = 0; s < shots; s++) {\n"
        "        run_shot();\n"
        "        unsigned out = 0;\n"
        "        for (unsigned b = 0; b < NB; b++) if (bits[b]) out |= (1u << b);\n"
        "        if (out < NUM_OUTCOMES) counts[out]++;\n"
        "    }\n"
        "    for (unsigned v = 0; v < NUM_OUTCOMES; v++) {\n"
        "        if (counts[v]) printf(\"%%u %%u\\n\", v, counts[v]);\n"
        "    }\n"
        "    return 0;\n"
        "}\n");
}

int aot_compile_and_run(const tir_module_t *M, uint32_t shots,
                        uint32_t *counts, uint32_t num_outcomes,
                        FILE *progress)
{
    assert(M != NULL);
    assert(counts != NULL);

    if (progress != NULL) {
        (void)fprintf(progress,
            "ERNESTAO START  insts=%u  shots=%u  qubits=%u  bits=%u\n",
            (unsigned)M->num_insts, (unsigned)shots,
            (unsigned)tir_total_qubits(M),
            (unsigned)tir_total_bits(M));
    }

    /* Codegen. */
    FILE *fp = fopen(AOT_TEMP_C, "w");
    if (fp == NULL) {
        if (progress != NULL) {
            (void)fprintf(progress,
                "ERNESTAO CODEGEN  RC=8  cannot open %s for write\n",
                AOT_TEMP_C);
        }
        return 1;
    }
    emit_prelude(M, fp, shots);
    emit_run_shot(M, fp);
    emit_main(fp);
    (void)fclose(fp);
    if (progress != NULL) {
        (void)fprintf(progress,
            "ERNESTAO CODEGEN  RC=0  wrote %s\n", AOT_TEMP_C);
    }

    /* Compile with gcc. */
    if (progress != NULL) {
        (void)fprintf(progress, "ERNESTAO GCC      cmd=%s\n", AOT_GCC_CMD);
    }
    int rc = system(AOT_GCC_CMD);
    if (rc != 0) {
        if (progress != NULL) {
            (void)fprintf(progress, "ERNESTAO GCC      RC=%d FAILED\n", rc);
        }
        return 2;
    }
    if (progress != NULL) {
        (void)fprintf(progress, "ERNESTAO GCC      RC=0\n");
    }

    /* Execute and capture stdout. */
    char cmd[256];
    (void)snprintf(cmd, sizeof cmd, "%s %u", AOT_RUN_CMD, (unsigned)shots);
    FILE *binp = popen(cmd, "r");
    if (binp == NULL) {
        if (progress != NULL) {
            (void)fprintf(progress, "ERNESTAO EXEC     RC=8 popen failed\n");
        }
        return 3;
    }

    /* Zero the caller's count array. */
    for (uint32_t i = 0u; i < num_outcomes; i++) {
        counts[i] = 0u;
    }

    /* Parse "outcome count" lines from the binary's stdout. */
    char line[128];
    uint32_t lines_parsed = 0u;
    while (fgets(line, (int)sizeof line, binp) != NULL) {
        unsigned outcome, count;
        if (sscanf(line, "%u %u", &outcome, &count) == 2) {
            if (outcome < num_outcomes) {
                counts[outcome] += count;
            }
            lines_parsed++;
        }
    }
    (void)pclose(binp);

    if (progress != NULL) {
        (void)fprintf(progress,
            "ERNESTAO EXEC     RC=0  outcomes_seen=%u\n",
            (unsigned)lines_parsed);
        (void)fprintf(progress, "ERNESTAO ENDED    RC=0\n");
    }
    return 0;
}
